"""Add missing acquisition fields and Fund model

Revision ID: 8dfaea897107
Revises: 827104d5f215
Create Date: 2025-10-27 15:38:13.117526

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '8dfaea897107'
down_revision: Union[str, None] = '827104d5f215'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('funds',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('code', sa.String(length=50), nullable=False),
    sa.Column('name', sa.String(length=255), nullable=False),
    sa.Column('description', sa.String(length=500), nullable=True),
    sa.Column('fund_status', sa.String(length=50), nullable=True),
    sa.Column('fund_type', sa.String(length=50), nullable=True),
    sa.Column('allocated_amount', sa.Numeric(precision=10, scale=2), nullable=True),
    sa.Column('currency', sa.String(length=3), nullable=True),
    sa.Column('created_date', sa.DateTime(timezone=True), nullable=False),
    sa.Column('updated_date', sa.DateTime(timezone=True), nullable=True),
    sa.Column('tenant_id', sa.UUID(), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_funds_code'), 'funds', ['code'], unique=True)
    op.create_index(op.f('ix_funds_tenant_id'), 'funds', ['tenant_id'], unique=False)
    op.add_column('orders', sa.Column('po_number', sa.String(length=100), nullable=False))
    op.add_column('orders', sa.Column('workflow_status', sa.String(length=50), nullable=True))
    op.add_column('orders', sa.Column('order_type', sa.String(length=50), nullable=True))
    op.add_column('orders', sa.Column('approved', sa.Boolean(), nullable=True))
    op.add_column('orders', sa.Column('total_estimated_price', sa.Numeric(precision=10, scale=2), nullable=True))
    op.add_column('orders', sa.Column('total_items', sa.String(length=50), nullable=True))
    op.add_column('orders', sa.Column('ship_to', sa.String(length=500), nullable=True))
    op.add_column('orders', sa.Column('bill_to', sa.String(length=500), nullable=True))
    op.drop_index('ix_orders_order_number', table_name='orders')
    op.create_index(op.f('ix_orders_po_number'), 'orders', ['po_number'], unique=True)
    op.drop_column('orders', 'order_number')
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('orders', sa.Column('order_number', sa.VARCHAR(length=100), autoincrement=False, nullable=False))
    op.drop_index(op.f('ix_orders_po_number'), table_name='orders')
    op.create_index('ix_orders_order_number', 'orders', ['order_number'], unique=True)
    op.drop_column('orders', 'bill_to')
    op.drop_column('orders', 'ship_to')
    op.drop_column('orders', 'total_items')
    op.drop_column('orders', 'total_estimated_price')
    op.drop_column('orders', 'approved')
    op.drop_column('orders', 'order_type')
    op.drop_column('orders', 'workflow_status')
    op.drop_column('orders', 'po_number')
    op.drop_index(op.f('ix_funds_tenant_id'), table_name='funds')
    op.drop_index(op.f('ix_funds_code'), table_name='funds')
    op.drop_table('funds')
    # ### end Alembic commands ###
